#!/usr/bin/env php
<?php

declare(strict_types=1);

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput());

exit($status);
